# -*- coding: utf-8 -*-
"""exercise_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NefJ5DuaH5AXrkbW0vi25jXXEn51EN2n
"""

#Proyecto 1 - Problema 2
import math
class sis_estatico:
  def __init__(self, a1 = 0, a2 = 0, N = 0):
    self.a1 = a1
    self.a2 = a2
    self.N = N
    self.tensiones = dict()
    self.tensiones_calc()
  def tensiones_calc(self):
    conv = math.pi/180
    k = (self.N)/(math.tan(self.a1*conv)+math.tan(self.a2*conv))
    T1 = k/math.cos(self.a1*conv)
    T2 = k/math.cos(self.a2*conv)
    self.tensiones["Tensión 1"] = T1
    self.tensiones["Tensión 2"] = T2
    return self.tensiones

sistema1= sis_estatico(a1 = 25,
                       a2 = 60,
                       N = 490)

sistema1.tensiones