# -*- coding: utf-8 -*-
"""exercise_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rLLsNYzD_lN7ur_hyKBAuAMlLEBbQO-L
"""

#Proyecto 1 - Problema 4
import math
class sist_dinamico:
  def __init__(self, a1 = 0, a2 = 0, e = 0,  N=0):
    self.a1 = math.radians(a1)
    self.a2 = math.radians(a2)
    self.N = N
    self.e = e/100
    self.angulos_finales = dict()
    self.angulo_final()
  def __calc_angulo_final(self, ang1, ang2, e):
    a_f = 0
    if e == 0.015 or e == 0.1 or e == 0.4 or e == 0:
      k1 = math.sin(ang1)/math.tan(ang2) + math.cos(ang1)
      k2 = 1 - math.pow(math.sin(ang1), 2)/math.pow(math.sin(ang2), 2)
      a_f = math.acos((math.pow(k1, 2) + math.pow((1+e), 2)*k2)/(2*(1+e)*k1))
      a_f = math.degrees(a_f)
    else:
      print("elongación no válida, devolvemos valor cero")
    return a_f

  def angulo_final(self):
    self.angulos_finales["Angulo final 1"] = self.__calc_angulo_final(self.a1, self.a2, self.e)
    self.angulos_finales["Angulo final 2"] = self.__calc_angulo_final(self.a2, self.a1, self.e)
    return self.angulos_finales

sist1 = sist_dinamico(a1 = 30.96,
                      a2 = 45,
                      e = 40)

sist1.angulos_finales